import {
  MatchStrengthIcon,
  ProfileIcon,
  ShortlistIcon,
  HumanReviewIcon,
  LockIcon,
  ScaleIcon,
  VerifiedIcon,
  ContactIcon,
  DocumentIcon,
  ShieldIcon,
  InfoIcon,
  type IconProps,
} from "@/components/icons";
import type { ComponentType } from "react";

export type Block =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] };

export type Doc = {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  icon: ComponentType<IconProps>;
  body: Block[];
};

export type DocGroup = {
  label: string;
  slugs: string[];
};

const p = (text: string): Block => ({ type: "p", text });
const h2 = (text: string): Block => ({ type: "h2", text });
const h3 = (text: string): Block => ({ type: "h3", text });
const ul = (items: string[]): Block => ({ type: "ul", items });
const ol = (items: string[]): Block => ({ type: "ol", items });

export const DOCS: Doc[] = [
  {
    slug: "how-matching-works",
    title: "How matching works",
    subtitle: "An overview of how Appointed matches people to roles.",
    description: "The methodology behind every candidate match.",
    icon: MatchStrengthIcon,
    body: [
      p("Appointed's matching engine is the core of the platform. It takes a role's requirements and a candidate's profile, scores how well they fit each other, and produces a transparent, criterion-by-criterion explanation of the match."),
      p("This document explains the methodology at a level appropriate for hiring teams, compliance reviewers, and anyone doing technical evaluation. Detailed mathematical specifications are available under NDA for enterprise customers."),
      h2("What the matching engine considers"),
      p("For every match, the engine evaluates the candidate's profile against the role on a defined set of criteria. The criteria fall into seven categories:"),
      ol([
        "Skills. The role's required and preferred skills, matched against the candidate's stated and verified skills.",
        "Experience. Years of experience overall and in relevant roles, type of organizations, scale of responsibility.",
        "Education. Required or preferred degrees, fields of study, institutions, recency.",
        "Languages. Required languages and proficiency levels.",
        "Location and mobility. Candidate's current location, willingness to relocate, hybrid or remote preferences, commutable distance.",
        "Authorization. Work authorization status for the country where the role is based.",
        "Compensation fit. The candidate's stated salary range against the role's offered range.",
      ]),
      p("Each criterion is weighted according to the role's stated priorities. The hiring team can see and adjust the weights for their role. The platform's defaults are calibrated by industry and role type."),
      h2("What the matching engine does not consider"),
      p("The engine does not analyze, infer, or score:"),
      ul([
        "Personality traits, communication style, or tone of voice",
        "Photos or facial expressions",
        "Inferred demographics or protected characteristics",
        "Cultural fit, attitude, or vibe",
        "Anything not explicitly stated in the candidate's profile or the role's requirements",
      ]),
      p("This is a deliberate design choice. Recruitment AI that infers traits beyond what candidates state has consistently been shown to produce biased and unreliable outputs. Appointed matches on what it can verify and explain, not on guesses."),
      h2("How matches are explained"),
      p("Every match produced by the engine comes with a reasoning breakdown. The hiring team sees how the candidate scored on each criterion, what fits well, what fits partially, and what does not fit. The candidate, if matched, sees the same reasoning when a contact request reaches them."),
      p("The reasoning is generated from the same scoring logic the engine uses. It is not a separate explanation layer that may diverge from the actual decision. If the engine cannot explain why a match was made, the match does not happen."),
      h2("How matches are ordered"),
      p("Within a role's eligible pool, matches are ranked by overall score with two adjustments:"),
      ul([
        "Candidates with profiles updated in the last 60 days are prioritized over candidates with older profiles.",
        "Candidates with verified credentials are prioritized over candidates with unverified credentials of similar match strength.",
      ]),
      p("Both of these adjustments are bias-tested quarterly to ensure they do not produce disparate impact across protected categories. See the Fairness and bias testing document for details."),
      h2("Human oversight"),
      p("The matching engine produces recommendations, not decisions. Every candidate has the right to request human review of any match they appear in (or do not appear in). Every hiring team is responsible for the final decision to contact a candidate. Appointed provides the infrastructure for that decision; the human makes it."),
    ],
  },
  {
    slug: "the-candidate-journey",
    title: "The candidate journey",
    subtitle: "From profile creation to job conversation.",
    description: "What individuals experience on the platform.",
    icon: ProfileIcon,
    body: [
      p("A candidate's experience on Appointed is structured around a single principle: the platform works in the background, and the candidate stays in control of what happens next."),
      h2("Building a profile"),
      p("Candidates create an account and complete a structured profile covering experience, skills, education, languages, location, work authorization, and preferences including salary expectations. The profile takes around 15 minutes for the basics."),
      p("Profiles are not visible to recruiters by default. They sit in the platform's matching pool, where the engine will compare them against future role postings."),
      h2("Verification"),
      p("Candidates can verify their identity, education credentials, and work history through Appointed's trusted EU verification partners. Verification is free for candidates. Verified profiles are prioritized in shortlists because hiring teams trust them more."),
      p("Verification is optional and progressive. A candidate can verify their identity first, add education verification later, and verify employment history when convenient. Each verified item strengthens the profile."),
      h2("Matching"),
      p("When a hiring team posts a role, the matching engine scores every consenting profile against the role's requirements. Candidates who match strongly enough are added to the role's shortlist with full reasoning attached."),
      p("At this stage, the candidate is identified to the hiring team only by their skills, experience, and reasoning. Their name, photo, and contact details are not visible."),
      h2("Consent to contact"),
      p("When a hiring team wants to contact a matched candidate, the platform first notifies the candidate. The notification includes the role title, the company name, the location, a role summary, the salary range if posted, and the AI's reasoning for the match."),
      p("The candidate has time to decide. If they approve, their name and contact details are released to the hiring team and the hiring team's message reaches the candidate. If they decline, no contact happens. If they do not respond, the slot is replaced and they can re-engage with future matches."),
      p("This consent gate exists because being matched to a role is not the same as wanting to be contacted about it. Appointed does not assume the second from the first."),
      h2("Direct conversation"),
      p("Once a candidate approves contact, the conversation between candidate and hiring team happens directly. Appointed does not mediate, score, or analyze the conversation. The platform's job ends at the moment of mutual interest."),
      h2("Ongoing matching"),
      p("Candidates remain in the matching pool as long as their profile is active. They receive new matches as new roles are posted. They can pause their matches at any time, update their profile to improve match quality, or delete their account if they no longer want to participate."),
      h2("Rights and controls"),
      p("Candidates can at any time:"),
      ul([
        "See every match they have appeared in, contacted or not",
        "Request human review of any AI decision about their profile",
        "Export their data",
        "Correct or update their profile",
        "Pause matching",
        "Delete their account",
      ]),
      p("Every action a candidate takes is logged for their own visibility. Every action the platform takes is logged for audit."),
    ],
  },
  {
    slug: "the-hiring-team-experience",
    title: "The hiring team experience",
    subtitle: "Posting roles, reviewing matches, hiring.",
    description: "What recruiters and hiring teams do on the platform.",
    icon: ShortlistIcon,
    body: [
      p("The hiring team's experience on Appointed is structured around delivering a curated shortlist for each role and supporting the team's decisions with clear reasoning."),
      h2("Account provisioning"),
      p("Appointed is not self-serve for hiring teams. Access begins with a short conversation that establishes mutual fit, after which the team's account is provisioned. This conversation is also where the pricing, service terms, and compliance arrangements are reviewed."),
      h2("Posting a role"),
      p("The role posting flow asks for structured information: title, location, employment type, seniority, required and preferred skills, experience level, education, languages, work authorization, and compensation range. The team can adjust the weights of these criteria for their specific role."),
      p("The team can also define hard filters (criteria that are non-negotiable, like specific certifications or work authorization) separately from preferences (criteria that influence match strength but do not exclude candidates)."),
      p("The role description is not a marketing document. The matching engine works on the structured criteria, not on the narrative description. The team writes a description for the candidates who receive contact requests, but the matching is driven by the structured fields."),
      h2("Receiving the shortlist"),
      p("Within minutes of posting, the platform delivers a shortlist of pre-matched candidates. The default shortlist size is eight, adjustable between five and fifteen."),
      p("Each candidate appears with:"),
      ul([
        "An anonymized identifier",
        "Current role and years of experience",
        "Location",
        "Match strength score",
        "Criterion-by-criterion reasoning",
        "Verification badges",
        "Top reasoning points clearly visible",
      ]),
      p("Candidates are anonymized to the hiring team at this stage. The team sees skills, experience, and reasoning, not names or contact details."),
      h2("Reviewing candidates"),
      p("The hiring team reviews each candidate's profile and reasoning. They can request the full profile view to see more detail. They can refine the criteria and regenerate the shortlist if the batch is not the right fit. There are no quotas on regeneration."),
      h2("Contacting candidates"),
      p("When the team decides to contact a candidate, they write a personalized message and submit the contact request. The platform notifies the candidate, who decides whether to accept."),
      p("If the candidate accepts, their name and contact details are released to the hiring team and the message is delivered. If the candidate declines or does not respond, the platform automatically surfaces a replacement candidate from the reserve of next-ranked profiles, so the team's working shortlist stays full."),
      p("The team sees clear status indicators on every contact request and never has to wait on an inactive slot."),
      h2("Direct conversation"),
      p("Once contact is approved, the team communicates with the candidate directly outside the platform. Appointed does not relay or analyze messages between the team and the candidate."),
      h2("Reporting a hire"),
      p("When a team hires a candidate sourced through Appointed, they mark the hire in the platform. This triggers the placement workflow and ensures attribution is recorded for the service agreement. Disputes are handled by a brief human review process described in the service terms."),
      h2("Compliance documentation"),
      p("Every account has access to the platform's compliance documentation, including bias testing reports, audit trail evidence, DPIA inputs, and the AI Act deployer guidance. Hiring teams use these documents for their own procurement, legal, and compliance processes."),
      h2("Team management"),
      p("Hiring teams can invite teammates with role-based access: admin (full access), recruiter (post roles, contact candidates), and viewer (read-only). Every team member's actions are logged."),
    ],
  },
  {
    slug: "consent-and-contact",
    title: "The consent and contact process",
    subtitle: "Where consent is required, how it is obtained, and what changes when it is given.",
    description: "How candidate consent works at every stage.",
    icon: ContactIcon,
    body: [
      p("Appointed is built around the principle that personal data is shared only with explicit consent at each meaningful stage. This document walks through every consent point in the platform."),
      h2("Consent at profile creation"),
      p("When a candidate creates an account, they are asked for three separate, unbundled consents:"),
      ul([
        "Consent to store their profile and use it for matching",
        "Consent to verification of identity and credentials through trusted EU partners (optional)",
        "Consent to receive product updates (optional)",
      ]),
      p("Each consent is granular. Candidates can revoke any consent at any time without losing the account. Without matching consent, the profile is stored but not used; without verification consent, verification does not happen; without product update consent, no marketing emails are sent."),
      h2("Consent before contact"),
      p("When a hiring team wants to contact a matched candidate, the platform does not release the candidate's name or contact details automatically. Instead, the platform sends the candidate a contact request notification."),
      p("The notification contains:"),
      ul([
        "The role title and company name",
        "The role location and a short description",
        "The compensation range if posted",
        "The AI's reasoning for the match",
      ]),
      p("The candidate has a window of time to decide. The exact window is short enough to support recruiter velocity and long enough to give candidates reasonable time to respond."),
      p("The candidate's options are:"),
      ul([
        "Approve the contact: name and contact details are released, and the hiring team's message is delivered.",
        "Decline the contact: no information is shared, the hiring team is notified that the slot has been replaced, and no reason is given to them.",
        "Do not respond: the request expires, the slot is replaced, and the candidate can re-engage with future matches.",
      ]),
      p("The platform does not pressure the candidate, does not show countdown timers, and does not penalize a decline. Declines and expirations are treated the same way: a quiet replacement of the slot."),
      h2("Consent posture for the recruiter"),
      p("The hiring team does not see the reason a candidate declined or expired a request. They only see that the slot has been replaced. This protects candidate privacy and prevents hiring teams from learning patterns that could be used to identify candidates who declined."),
      h2("Direct contact preference"),
      p("Candidates can opt into a faster mode where they are contacted directly without the consent gate. This is useful for actively job-seeking candidates who want to maximize engagement. The setting is changeable at any time."),
      p("The default is consent-gated. The faster mode is opt-in only."),
      h2("Profile pause"),
      p("Candidates can pause their participation in matching at any time. While paused, their profile is excluded from new shortlists. They can resume by toggling the setting. This is useful for vacations, periods of stability, or any time the candidate does not want new contacts."),
      h2("Audit trail"),
      p("Every consent action (granted, declined, expired, revoked) is logged in the candidate's history and in the platform's audit trail. Candidates can see their own consent history at any time. Platform staff can review consent history during audits and contests, but not for casual browsing."),
      h2("Data minimization at each stage"),
      p("Before consent to contact, the hiring team sees only what is needed to evaluate fit. After consent to contact, the team sees only what is needed to begin the conversation. The platform does not share more than the next step requires."),
    ],
  },
  {
    slug: "data-and-privacy",
    title: "Data and privacy",
    subtitle: "Appointed's data handling, summarized for legal and compliance reviewers.",
    description: "What we collect, store, share, and protect.",
    icon: LockIcon,
    body: [
      p("This document describes how Appointed handles personal data. A full data processing addendum is available to customers as part of the service agreement."),
      h2("Data we collect"),
      h3("For candidates"),
      ul([
        "Profile data (experience, skills, education, languages, preferences, salary expectations)",
        "Contact information (name, email, phone if provided)",
        "Identity verification data (handled by KYC partners; only verification status stored)",
        "Credential verification data (handled by verification partners; only result stored)",
        "Activity data (logins, profile updates, matches, consent actions)",
      ]),
      h3("For hiring teams"),
      ul([
        "Team and company information",
        "Role postings",
        "Activity data (job posts, candidate views, contact requests, status updates)",
        "Hire confirmations",
      ]),
      h2("Data we do not collect"),
      ul([
        "Biometric data",
        "Inferred demographic data",
        "Voice or video analysis",
        "Browsing data beyond what is needed for security",
        "Third-party social media profiles unless the candidate connects them",
      ]),
      h2("Where data is stored"),
      p("All personal data is stored on infrastructure located in the European Union. Data is encrypted at rest using industry-standard AES-256 and in transit using TLS 1.3 or higher. Access is controlled by role-based authentication with audit logging on every read."),
      h2("Who can access data"),
      h3("Within Appointed"),
      ul([
        "Engineering staff for system maintenance, with logged access only and on a need-to-know basis",
        "Customer-facing staff for support, with logged access and customer consent for case-specific reviews",
        "Compliance and audit staff for required reviews",
        "Data protection officer for rights requests and incidents",
      ]),
      h3("Outside Appointed"),
      ul([
        "Hiring teams see anonymized profiles in shortlists and full profiles only after candidate consent",
        "Verification partners receive only the data needed for verification, with their own EU compliance posture",
        "No data is sold, shared with advertisers, or shared with third parties outside the matching and verification flow",
      ]),
      h2("Data retention"),
      p("Active profiles are retained as long as the candidate maintains the account. Inactive profiles (no login for 12 months) are flagged for the candidate's attention and, if still inactive after a further 6 months, are anonymized and removed from matching."),
      p("Hiring team data is retained for the duration of the service agreement plus the period required by accounting and tax law (typically 10 years for invoicing records, anonymized after)."),
      p("Audit logs are retained for 5 years for regulatory compliance."),
      p("Deleted accounts have personal data removed within 30 days. Anonymized statistical records may persist for fairness testing and platform operations."),
      h2("Candidate rights"),
      p("Candidates have the right to:"),
      ul([
        "Access their data",
        "Correct inaccurate data",
        "Delete their account and associated data",
        "Export their data in a portable format",
        "Object to specific processing",
        "Request human review of any automated decision",
        "Lodge a complaint with a supervisory authority",
      ]),
      p("Rights requests are handled by the data protection officer at dpo@appointed.com and resolved within 30 days."),
      h2("Hiring team rights"),
      p("Hiring teams have analogous rights for the data they have provided to the platform. Specifically, they can review and update their data, export records, and terminate their account subject to the service agreement terms."),
      h2("Sub-processors"),
      p("Appointed uses a small number of sub-processors for infrastructure, verification, and support functions. The current list is maintained on request. All sub-processors are required to meet Appointed's data protection standards and are bound by data processing agreements."),
      h2("Breach notification"),
      p("In the event of a data breach affecting personal data, Appointed will notify affected parties without undue delay and in any event within 72 hours of becoming aware of the breach, as required by GDPR. Customers and candidates will be notified directly when their data is involved."),
      h2("Data protection officer"),
      p("The data protection officer can be reached at dpo@appointed.com for any privacy-related question, rights request, or concern."),
    ],
  },
  {
    slug: "eu-ai-act-compliance",
    title: "EU AI Act compliance",
    subtitle: "Appointed's approach to the EU Artificial Intelligence Act.",
    description: "How Appointed meets high-risk AI obligations.",
    icon: ScaleIcon,
    body: [
      p("The European Artificial Intelligence Act (Regulation 2024/1689) is the most comprehensive AI regulation in force globally. Appointed is built around the AI Act's requirements from the foundation."),
      h2("Classification"),
      p("Appointed's matching engine is an AI system intended for the recruitment and selection of natural persons. Under Annex III, Section 4 of the AI Act, this is classified as a high-risk AI system."),
      p("High-risk classification triggers strict obligations on the provider (Appointed) and the deployer (the hiring team using the platform). Appointed takes the heavier provider-side obligations and provides the documentation deployers need for their own obligations."),
      h2("Appointed's provider obligations"),
      p("As the provider of a high-risk AI system, Appointed maintains:"),
      ul([
        "A risk management system covering the AI's lifecycle (Article 9)",
        "Data governance practices including bias detection and mitigation (Article 10)",
        "Technical documentation describing the system's design, purpose, and limitations (Article 11)",
        "Automatic logging of system events for traceability (Article 12)",
        "Transparency information for deployers and candidates (Article 13)",
        "Human oversight mechanisms (Article 14)",
        "Accuracy, robustness, and cybersecurity measures (Article 15)",
        "A quality management system covering compliance procedures (Article 17)",
        "Post-market monitoring and incident reporting (Articles 72 and 73)",
        "CE marking and registration in the EU AI database before deployment",
      ]),
      h2("Hiring team deployer obligations"),
      p("As deployers, hiring teams using Appointed are responsible for:"),
      ul([
        "Using the system as intended and within its declared capabilities",
        "Exercising appropriate human oversight",
        "Informing candidates that AI is involved in matching",
        "Conducting their own fundamental rights impact assessment where required",
        "Maintaining their own records of use",
        "Reporting serious incidents related to their use of the system",
      ]),
      p("Appointed provides documentation, guidance, and templates to help deployers meet these obligations. The deployer guidance is included in the customer onboarding process."),
      h2("Human oversight in practice"),
      p("Appointed's matching engine produces recommendations. The decision to contact a candidate is made by the hiring team. The decision to engage with a contact is made by the candidate. The platform's role is to surface matches and explain them; the human role is to act on them."),
      p("When a candidate disagrees with how the AI handled their profile for a specific role, they can request human review. A trained reviewer on Appointed's compliance team examines the decision, the reasoning, and the candidate's profile, then responds within 14 days with an explanation and, where applicable, a corrected outcome."),
      h2("Transparency"),
      p("Candidates and hiring teams are informed about the use of AI in matching at multiple points: at signup, in the privacy notice, in the about and documentation pages, in match notifications, and in the audit trail. The AI's reasoning is visible to both sides of every match."),
      h2("Logging"),
      p("Every AI decision is logged with timestamp, inputs, outputs, and reasoning. Logs are retained for the period required by the AI Act and are available for regulatory inspection. Customers can request audit log extracts for their own deployer obligations."),
      h2("Bias testing"),
      p("The matching engine is bias-tested quarterly across protected categories and proxy signals. See the Fairness and bias testing document for methodology and results structure."),
      h2("Conformity assessment and CE marking"),
      p("Appointed has completed (or, as deadlines apply, is in the process of completing) the conformity assessment required for high-risk AI systems. The system is registered in the EU AI database and bears the CE marking required by the Act."),
      h2("Updates to this document"),
      p("This document is updated as the AI Act's implementation progresses, as Appointed's compliance evidence accumulates, and as the Commission's guidance evolves. The current version date is shown in the document footer."),
      p("For specific compliance questions, contact compliance@appointed.com."),
    ],
  },
  {
    slug: "fairness-and-bias-testing",
    title: "Fairness and bias testing",
    subtitle: "How Appointed measures and corrects bias in matching.",
    description: "Our methodology for testing and correcting bias.",
    icon: HumanReviewIcon,
    body: [
      p("Bias in recruitment AI is a documented and serious problem. Appointed treats fairness as a measurable property of the platform, not as a marketing claim. This document describes the methodology used to test and correct bias."),
      h2("What we test"),
      p("The matching engine is tested for disparate impact across protected categories and proxy signals."),
      h3("Protected categories (where data is available with appropriate legal basis)"),
      ul([
        "Age band",
        "Gender (where declared)",
        "Nationality",
        "Estimated socioeconomic background (via proxies, where statistically valid)",
      ]),
      h3("Proxy signals (non-protected signals that may correlate with protected categories)"),
      ul([
        "Profile freshness (recently updated vs dormant)",
        "Verification status (verified vs unverified)",
        "Profile completeness",
        "Language profile",
        "Career path patterns",
      ]),
      p("For each category and signal, we measure:"),
      ul([
        "Selection rate (the rate at which candidates in a category appear in shortlists)",
        "Score distribution (the distribution of match scores within a category)",
        "Contact rate (the rate at which candidates in a category are contacted by hiring teams)",
        "Approval rate (the rate at which candidates in a category approve contact requests)",
      ]),
      p("We compare these rates across categories and apply standard statistical tests for disparate impact."),
      h2("The thresholds we apply"),
      p("We use the four-fifths rule as a baseline indicator: if the selection rate for a category is less than 80% of the rate for the highest category, this is treated as presumptive evidence of disparate impact and triggers investigation."),
      p("We also use chi-square tests, mean difference tests on score distributions, and intersectional analysis to catch patterns that the four-fifths rule alone might miss."),
      h2("What we do when we find disparate impact"),
      p("When a test detects disparate impact, the response depends on the source:"),
      ul([
        "If the cause is a specific weight in the matching engine (for example, profile freshness being weighted too heavily), the weight is adjusted and the test re-run.",
        "If the cause is a structural pattern in the data (for example, certain qualifications being more common in certain demographics), the engine is recalibrated to reduce reliance on that pattern.",
        "If the cause is a specific signal showing strong proxy correlation, the signal's weight is reduced or the signal is removed entirely.",
      ]),
      p("Every adjustment is logged, documented, and re-tested. We do not \"fix\" by hiding the result; we fix by correcting the system and re-measuring."),
      h2("Frequency"),
      p("Full bias tests are run quarterly. Targeted tests are run more frequently when changes are made to the matching engine. Results are reviewed by the compliance team and signed off by the data protection officer before deployment of any matching engine changes."),
      h2("Documentation"),
      p("Quarterly bias test results are summarized in a report available to customers as part of the compliance documentation package. The report includes:"),
      ul([
        "Categories tested",
        "Methodology applied",
        "Results summary",
        "Findings of disparate impact, if any",
        "Corrective actions taken",
        "Sign-off and version information",
      ]),
      p("Detailed statistical results are available to customers under NDA on request."),
      h2("Limitations"),
      p("We are transparent about the limitations of bias testing:"),
      ul([
        "Some protected categories are not collected by the platform (race, ethnicity, religion, sexual orientation, disability) because we do not need that data for matching and would not be authorized to use it. Bias on these dimensions cannot be measured directly within the platform and is approached through proxy analysis and structural design choices.",
        "Statistical tests detect aggregate patterns. Individual cases of bias may exist that do not show up at the aggregate level.",
        "Bias testing measures the matching engine, not the hiring team's decisions. The platform cannot test whether a hiring team's contact and hire decisions are themselves biased.",
        "Bias testing measures what we can observe. Decisions taken outside the platform (interviews, offers, accepted positions) are not visible to the engine.",
      ]),
      p("These limitations are why bias testing is one part of a broader fairness posture that includes structural design (no personality scoring, no biometric data, no inferred traits), candidate rights (consent gates, human review, transparency), and ongoing methodology improvement."),
      h2("Methodology evolution"),
      p("Bias testing methodology is reviewed annually and updated as research and regulatory guidance evolve. The current methodology version is shown in the quarterly report."),
    ],
  },
  {
    slug: "verification-and-credentials",
    title: "Verification and credentials",
    subtitle: "Appointed's approach to verifying who candidates are and what they have done.",
    description: "How identity and qualifications are verified.",
    icon: VerifiedIcon,
    body: [
      p("Verification is one of Appointed's strongest differentiators. Most recruitment platforms accept claims at face value. Appointed verifies them through trusted EU partners, with the candidate's consent, and surfaces verification status to hiring teams."),
      h2("What can be verified"),
      p("Three categories of credentials are supported:"),
      ol([
        "Identity verification. Confirms that the candidate is who they say they are. Performed by EU-licensed KYC providers using government-issued identity documents and biometric matching against the document photo. Verification result is stored; document images are not retained beyond the verification window.",
        "Education verification. Confirms that the candidate holds the qualifications they claim. Performed through direct verification with the issuing institution where possible, or through certificate verification services for institutions that have API-based verification. Manual document review with issuer confirmation is used as a fallback.",
        "Employment history verification. Confirms that the candidate held the roles they claim. Performed through direct contact with previous employers, with the candidate's authorization, or through employment verification services where available. Dates and titles are verified; performance reviews and salary are not collected.",
      ]),
      h2("How verification works for candidates"),
      p("Candidates can initiate verification at any time from their profile dashboard. The platform walks them through the process for each credential, collects the necessary information, and dispatches to the appropriate partner."),
      p("Each verification has its own timeline:"),
      ul([
        "Identity verification typically completes within minutes",
        "Education verification typically completes within 3-7 business days depending on the institution",
        "Employment verification typically completes within 5-10 business days depending on the previous employer's responsiveness",
      ]),
      p("Candidates can see the status of every verification in progress and are notified when each completes."),
      h2("How verification appears to hiring teams"),
      p("In shortlists and full profile views, hiring teams see verification badges for each verified credential. The badges indicate what was verified, when, and by which partner. Unverified credentials are shown without badges and may show a \"Self-reported\" indicator."),
      p("Verified profiles are prioritized in matching. The platform tells the hiring team clearly which candidates are verified and to what degree."),
      h2("Costs"),
      p("Verification is free for candidates. Appointed absorbs the verification cost as part of the platform's operating costs, recovered through the placement fees charged to hiring teams. Candidates are never asked to pay for verification."),
      h2("Partners"),
      p("Appointed uses established EU verification partners with their own compliance posture. The current list is available on request. All partners are bound by data processing agreements and meet GDPR's requirements for cross-border data handling within the EU."),
      h2("Limits"),
      p("Some credentials cannot be verified through standard channels:"),
      ul([
        "Qualifications from institutions that no longer exist",
        "Employment with companies that have ceased operations",
        "Self-employment or freelance work without external verification routes",
        "Credentials from countries outside Appointed's verification network",
      ]),
      p("In these cases, the credential remains on the profile as self-reported, and Appointed explores alternative verification options where the candidate requests it. The matching engine treats self-reported credentials with lower weight than verified credentials, which reflects the difference in trust."),
      h2("Re-verification"),
      p("Verifications expire on a defined schedule appropriate to the credential type:"),
      ul([
        "Identity verification: 24 months",
        "Education verification: indefinite (qualifications do not expire)",
        "Employment verification: 12 months for current employment, indefinite for past employment",
      ]),
      p("Candidates are notified before a verification expires and can re-verify with a single confirmation."),
      h2("Disputes"),
      p("If a candidate disputes a verification result, they can request manual review. The compliance team examines the verification data and the candidate's evidence, then issues a corrected status if applicable. Disputes are resolved within 14 days."),
    ],
  },
  {
    slug: "getting-started-for-hiring-teams",
    title: "Getting started for hiring teams",
    subtitle: "From first conversation to first hire.",
    description: "What to expect when joining Appointed.",
    icon: ContactIcon,
    body: [
      p("This document describes how a hiring team begins using Appointed, from the first contact through the first successful hire."),
      h2("Initial conversation"),
      p("A hiring team that wants to use Appointed starts by submitting a short request through the contact form. The request is reviewed by the Appointed team within one business day, and a 30-minute qualification call is scheduled."),
      p("The qualification call covers:"),
      ul([
        "The team's hiring patterns, sectors, and typical role types",
        "How Appointed's matching methodology aligns with their needs",
        "The pricing model and service terms",
        "Compliance and procurement considerations",
        "Practical onboarding next steps",
      ]),
      p("The call is mutual. Both sides are deciding whether the partnership is the right fit."),
      h2("Account provisioning"),
      p("If both sides are aligned, the team's account is provisioned the same day as the qualification call. The team receives:"),
      ul([
        "Login credentials for the platform",
        "A welcome email with key resources",
        "The service agreement for review and signature",
        "Access to the compliance documentation package",
      ]),
      p("The team's account is fully functional from the moment of provisioning. There is no setup fee and no monthly subscription."),
      h2("Onboarding session"),
      p("Within the first week of provisioning, an Appointed team member walks the hiring team through:"),
      ul([
        "How to post a role",
        "How to interpret matching reasoning",
        "How to manage the shortlist and consent process",
        "How to invite teammates and configure access",
        "How to use the compliance documentation",
      ]),
      p("The onboarding session is typically 45 minutes. It is collaborative, not didactic. The Appointed team learns about the hiring team's specific context and calibrates the matching engine accordingly."),
      h2("First role"),
      p("The team posts their first role following the onboarding. Within minutes, the first shortlist is delivered. The team reviews, contacts, and observes the platform's mechanics for the first time."),
      p("The Appointed team is closely engaged during the first 30 days, available for questions, calibration adjustments, and any issues that arise."),
      h2("First hire"),
      p("Most teams make their first hire through Appointed within 30-60 days of provisioning. When a hire happens, the team marks it in the platform. This triggers the placement workflow: confirmation of attribution, invoicing for the placement fee, and the start of the 90-day replacement guarantee window."),
      h2("Ongoing partnership"),
      p("After the first hire, the team operates the platform independently. The Appointed team remains available for:"),
      ul([
        "Calibration sessions when hiring patterns evolve",
        "Compliance updates as regulations and the team's needs change",
        "Quarterly bias test reports",
        "Any escalations, disputes, or questions",
      ]),
      p("For larger or higher-volume customers, a dedicated customer success manager is assigned."),
      h2("Expansion"),
      p("As the team's usage grows, additional capabilities become available:"),
      ul([
        "Custom matching calibration for specific role types",
        "ATS integration with major platforms",
        "Multi-team account structures for larger organizations",
        "High-volume subscription tier for teams hiring extensively through the platform",
      ]),
      p("These are introduced when they become relevant, not upsold."),
    ],
  },
  {
    slug: "service-terms-and-commitments",
    title: "Service terms and commitments",
    subtitle: "What hiring teams can expect from Appointed as a service provider.",
    description: "Our service commitments to hiring teams.",
    icon: DocumentIcon,
    body: [
      p("This document summarizes Appointed's service commitments. The full service agreement is provided at account provisioning and governs the contractual relationship."),
      h2("Platform availability"),
      p("Appointed commits to 99.5% platform availability measured monthly, excluding scheduled maintenance windows. Maintenance is announced at least 48 hours in advance and conducted outside European business hours where possible."),
      p("Outages of more than 4 consecutive hours during business hours are reported to affected customers within 1 hour of detection, with status updates every 2 hours until resolution."),
      h2("Match delivery"),
      p("For active roles with sufficient candidate pool depth, Appointed commits to delivering the first shortlist within 30 minutes of role posting. If insufficient candidates are available to deliver the requested shortlist size, the team is notified with a clear explanation and options to broaden criteria or wait for additional candidates to enter the pool."),
      h2("Support response times"),
      p("Standard support response times during European business hours (Monday through Friday, 9:00 to 18:00 CET):"),
      ul([
        "Critical issues (platform unavailable, data integrity issues): 1 hour",
        "High priority issues (specific role or candidate problems): 4 hours",
        "Standard questions: 1 business day",
      ]),
      p("For dedicated customer success accounts, response times are shorter and include named contacts reachable directly."),
      h2("Replacement guarantee"),
      p("If a candidate hired through Appointed leaves or is terminated within 90 days of their start date, Appointed will source a replacement at no additional placement fee. The replacement role must be substantially similar to the original role, and the team must notify Appointed within 14 days of the original hire's departure."),
      h2("Compliance documentation"),
      p("Appointed commits to maintaining current compliance documentation, including bias test reports, AI Act conformity evidence, and GDPR processing details. Documentation is updated at least quarterly, more frequently when regulatory changes require."),
      p("Customers may request specific documentation extracts for their own procurement and compliance processes at any time, with response within 5 business days."),
      h2("Data handling commitments"),
      p("Appointed commits to:"),
      ul([
        "Storing all personal data on EU-based infrastructure",
        "Encrypting data at rest and in transit using current industry standards",
        "Maintaining the data minimization principles described in the Data and privacy document",
        "Not selling, sharing for advertising, or otherwise commercializing customer or candidate data",
        "Notifying affected parties of any data breach within 72 hours of awareness",
      ]),
      h2("Termination and data return"),
      p("Customers can terminate the service agreement at any time with 30 days' written notice. On termination:"),
      ul([
        "Appointed provides an export of the customer's data within 14 days",
        "Customer data is deleted from active systems within 30 days",
        "Backups are deleted within 90 days",
        "Audit logs are retained for the period required by regulation, anonymized where possible",
      ]),
      h2("Limitations of liability"),
      p("Appointed's liability is limited as defined in the service agreement, typically to fees paid in the preceding 12 months. The service agreement details exclusions and special cases."),
      h2("Insurance"),
      p("Appointed maintains professional liability and data breach insurance appropriate to the platform's scale. Insurance certificates are available on request to enterprise customers."),
      h2("Service agreement updates"),
      p("The service agreement may be updated to reflect changes in regulation, infrastructure, or service offering. Material changes are communicated at least 30 days in advance. Customers may terminate within that notice period without penalty if they do not accept the changes."),
    ],
  },
  {
    slug: "security-and-infrastructure",
    title: "Security and infrastructure",
    subtitle: "Appointed's security posture and infrastructure overview.",
    description: "How we protect the platform and your data.",
    icon: ShieldIcon,
    body: [
      p("This document summarizes Appointed's security and infrastructure approach. A detailed security overview is available to customers under NDA."),
      h2("Infrastructure"),
      p("Appointed runs on EU-based cloud infrastructure provided by major European or EU-compliant cloud providers. All primary and backup data storage is located in the European Union."),
      p("The platform is built on a modern web architecture with separation between presentation, application, and data layers. Each layer is isolated and access-controlled."),
      h2("Data security"),
      p("Data is encrypted at rest using AES-256 and in transit using TLS 1.3 or higher. Database backups are encrypted using separate keys managed under strict access controls."),
      p("Personal data is segregated from operational data. Special category data is segregated further and accessed only through controlled pathways with elevated authentication."),
      h2("Access controls"),
      p("Access to production systems is restricted to a small number of authorized staff using multi-factor authentication. All production access is logged and reviewed."),
      p("Administrative access to customer or candidate data requires a logged purpose, role-appropriate authorization, and audit trail. Casual browsing of personal data is not possible."),
      h2("Authentication"),
      p("Candidates and hiring teams authenticate using email and password with optional multi-factor authentication. Password storage uses industry-standard hashing (Argon2 or equivalent). OAuth via Google and LinkedIn is supported with appropriate scope limits."),
      p("Enterprise customers can configure SSO with their identity provider."),
      h2("Monitoring"),
      p("The platform is continuously monitored for security events, performance issues, and anomalies. Security events are reviewed by the security team and escalated according to severity."),
      h2("Vulnerability management"),
      p("Appointed maintains a vulnerability management program including:"),
      ul([
        "Continuous dependency scanning",
        "Static and dynamic application security testing",
        "Periodic penetration testing by independent firms",
        "A responsible disclosure program for external researchers",
      ]),
      p("Critical vulnerabilities are patched within 24 hours of detection where remediation is available. High-severity vulnerabilities are patched within 7 days. Lower-severity vulnerabilities are patched in the next regular release cycle."),
      h2("Incident response"),
      p("Appointed maintains an incident response plan covering detection, containment, eradication, recovery, and post-incident review. The plan is tested annually."),
      p("In the event of a security incident affecting customer or candidate data, affected parties are notified without undue delay and in any event within 72 hours of awareness, as required by GDPR."),
      h2("Compliance and certifications"),
      p("Appointed is working toward formal certification under SOC 2 Type II and ISO 27001. Certifications status is updated in this document as it progresses."),
      p("Appointed complies with GDPR and the EU AI Act as detailed in their respective documents."),
      h2("Sub-processors and supply chain"),
      p("Appointed uses a limited number of sub-processors for infrastructure, verification, and support functions. Each sub-processor is reviewed for security posture, bound by data processing agreements, and listed publicly. Changes to the sub-processor list are communicated to customers in advance."),
      h2("Customer security responsibilities"),
      p("Customers are responsible for:"),
      ul([
        "Maintaining the security of their own credentials and devices",
        "Managing access controls for their own team members on the platform",
        "Reporting suspected security issues to Appointed promptly",
        "Complying with the security obligations in their service agreement",
      ]),
      p("Appointed provides guidance and tools to support customer security responsibilities."),
      h2("Bug bounty and responsible disclosure"),
      p("Appointed welcomes responsible disclosure of security vulnerabilities by external researchers. Contact security@appointed.com to coordinate."),
    ],
  },
  {
    slug: "frequently-asked-questions",
    title: "Frequently asked questions",
    subtitle: "Quick answers to questions we hear often.",
    description: "Common questions about the platform.",
    icon: InfoIcon,
    body: [
      h2("For candidates"),
      h3("Is Appointed free for candidates?"),
      p("Yes. Always. The platform is paid by the hiring teams that use it. Candidates are never asked to pay for accounts, matching, verification, or any platform feature."),
      h3("How long does it take to build a profile?"),
      p("Around 15 minutes for the basics. Verification runs in the background and takes a few days to a few weeks depending on the credentials being verified. You do not need to wait for verification to start being matched."),
      h3("What happens to my profile if I get a job through Appointed?"),
      p("You can pause your profile, leave it active for future opportunities, or delete it entirely. The choice is yours."),
      h3("Can I see which companies have viewed my profile?"),
      p("You see every match you appear in, every contact request, and every action taken on your profile. Hiring teams cannot view profiles without first being matched to them."),
      h3("What if the AI made a wrong decision about my profile?"),
      p("Every match has a \"Request human review\" option. A trained reviewer examines the decision and responds within 14 days with an explanation and, where applicable, a corrected outcome."),
      h3("Can I be matched to roles in countries other than where I live?"),
      p("Yes, if your preferences include them. Appointed supports EU-wide matching with work authorization filtering."),
      h2("For hiring teams"),
      h3("Why isn't Appointed self-serve?"),
      p("Because match quality and compliance partnership matter more than signup volume. The qualification process ensures we understand your hiring context before you post your first role and that we work with teams where Appointed can deliver real value."),
      h3("How fast do we get the first shortlist after posting a role?"),
      p("Within minutes for active roles with sufficient candidate depth. If insufficient candidates are available, we notify you with options to broaden criteria or wait for the pool to grow."),
      h3("What if the shortlist is not a fit?"),
      p("Reject the batch and regenerate with adjusted criteria. No quotas, no fees, no penalty."),
      h3("How do you handle data when we receive a candidate's contact details?"),
      p("The candidate has consented specifically to your team contacting them about that role. You are responsible for handling their data in compliance with GDPR from that point. Appointed provides guidance and templates to support compliant handling."),
      h3("Can we integrate Appointed with our ATS?"),
      p("Direct integrations with major platforms (Workday, SuccessFactors, Personio, Greenhouse, Lever) are available for higher-volume customers. Manual export to any ATS is supported for all customers."),
      h3("What if a candidate we hire does not work out within 90 days?"),
      p("We source a replacement at no additional placement fee, provided the original hire left or was terminated within 90 days and the replacement role is substantially similar."),
      h2("For everyone"),
      h3("Where is Appointed based?"),
      p("Germany. Data stays in the EU. Support is provided in English and German, with additional EU languages added as we grow."),
      h3("Who owns the data on the platform?"),
      p("Candidates own their profile data. Hiring teams own their role and team data. Appointed processes data on their behalf under the terms documented here. Nothing is sold to third parties."),
      h3("How can I contact Appointed?"),
      p("General: hello@appointed.com"),
      p("Compliance and data protection: dpo@appointed.com"),
      p("Press: press@appointed.com"),
      p("Security: security@appointed.com"),
    ],
  },
];

export const DOC_GROUPS: DocGroup[] = [
  {
    label: "How the platform works",
    slugs: [
      "how-matching-works",
      "the-candidate-journey",
      "the-hiring-team-experience",
      "consent-and-contact",
    ],
  },
  {
    label: "Trust and compliance",
    slugs: [
      "data-and-privacy",
      "eu-ai-act-compliance",
      "fairness-and-bias-testing",
      "verification-and-credentials",
    ],
  },
  {
    label: "Working with Appointed",
    slugs: [
      "getting-started-for-hiring-teams",
      "service-terms-and-commitments",
      "security-and-infrastructure",
      "frequently-asked-questions",
    ],
  },
];

export function getDoc(slug: string): Doc | undefined {
  return DOCS.find((d) => d.slug === slug);
}
