/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecruitersRouteImport } from './routes/recruiters'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndividualsRouteImport } from './routes/individuals'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTeamRouteImport } from './routes/r.team'
import { Route as RSignupRouteImport } from './routes/r.signup'
import { Route as RSigninRouteImport } from './routes/r.signin'
import { Route as RSettingsRouteImport } from './routes/r.settings'
import { Route as ROnboardingRouteImport } from './routes/r.onboarding'
import { Route as RDashboardRouteImport } from './routes/r.dashboard'
import { Route as RCompanyRouteImport } from './routes/r.company'
import { Route as RCandidatesRouteImport } from './routes/r.candidates'
import { Route as RBillingRouteImport } from './routes/r.billing'
import { Route as MatchesIdRouteImport } from './routes/matches.$id'
import { Route as RJobsNewRouteImport } from './routes/r.jobs.new'
import { Route as RJobsIdRouteImport } from './routes/r.jobs.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitersRoute = RecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsRoute = IndividualsRouteImport.update({
  id: '/individuals',
  path: '/individuals',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTeamRoute = RTeamRouteImport.update({
  id: '/r/team',
  path: '/r/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RSignupRoute = RSignupRouteImport.update({
  id: '/r/signup',
  path: '/r/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RSigninRoute = RSigninRouteImport.update({
  id: '/r/signin',
  path: '/r/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RSettingsRoute = RSettingsRouteImport.update({
  id: '/r/settings',
  path: '/r/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ROnboardingRoute = ROnboardingRouteImport.update({
  id: '/r/onboarding',
  path: '/r/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RDashboardRoute = RDashboardRouteImport.update({
  id: '/r/dashboard',
  path: '/r/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RCompanyRoute = RCompanyRouteImport.update({
  id: '/r/company',
  path: '/r/company',
  getParentRoute: () => rootRouteImport,
} as any)
const RCandidatesRoute = RCandidatesRouteImport.update({
  id: '/r/candidates',
  path: '/r/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const RBillingRoute = RBillingRouteImport.update({
  id: '/r/billing',
  path: '/r/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RJobsNewRoute = RJobsNewRouteImport.update({
  id: '/r/jobs/new',
  path: '/r/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RJobsIdRoute = RJobsIdRouteImport.update({
  id: '/r/jobs/$id',
  path: '/r/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/businesses': typeof BusinessesRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/imprint': typeof ImprintRoute
  '/individuals': typeof IndividualsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/recruiters': typeof RecruitersRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/matches/$id': typeof MatchesIdRoute
  '/r/billing': typeof RBillingRoute
  '/r/candidates': typeof RCandidatesRoute
  '/r/company': typeof RCompanyRoute
  '/r/dashboard': typeof RDashboardRoute
  '/r/onboarding': typeof ROnboardingRoute
  '/r/settings': typeof RSettingsRoute
  '/r/signin': typeof RSigninRoute
  '/r/signup': typeof RSignupRoute
  '/r/team': typeof RTeamRoute
  '/r/jobs/$id': typeof RJobsIdRoute
  '/r/jobs/new': typeof RJobsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/businesses': typeof BusinessesRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/imprint': typeof ImprintRoute
  '/individuals': typeof IndividualsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/recruiters': typeof RecruitersRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/matches/$id': typeof MatchesIdRoute
  '/r/billing': typeof RBillingRoute
  '/r/candidates': typeof RCandidatesRoute
  '/r/company': typeof RCompanyRoute
  '/r/dashboard': typeof RDashboardRoute
  '/r/onboarding': typeof ROnboardingRoute
  '/r/settings': typeof RSettingsRoute
  '/r/signin': typeof RSigninRoute
  '/r/signup': typeof RSignupRoute
  '/r/team': typeof RTeamRoute
  '/r/jobs/$id': typeof RJobsIdRoute
  '/r/jobs/new': typeof RJobsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/businesses': typeof BusinessesRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/imprint': typeof ImprintRoute
  '/individuals': typeof IndividualsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/recruiters': typeof RecruitersRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/matches/$id': typeof MatchesIdRoute
  '/r/billing': typeof RBillingRoute
  '/r/candidates': typeof RCandidatesRoute
  '/r/company': typeof RCompanyRoute
  '/r/dashboard': typeof RDashboardRoute
  '/r/onboarding': typeof ROnboardingRoute
  '/r/settings': typeof RSettingsRoute
  '/r/signin': typeof RSigninRoute
  '/r/signup': typeof RSignupRoute
  '/r/team': typeof RTeamRoute
  '/r/jobs/$id': typeof RJobsIdRoute
  '/r/jobs/new': typeof RJobsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/businesses'
    | '/compliance'
    | '/contact'
    | '/dashboard'
    | '/imprint'
    | '/individuals'
    | '/onboarding'
    | '/privacy'
    | '/privacy-policy'
    | '/profile'
    | '/recruiters'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/matches/$id'
    | '/r/billing'
    | '/r/candidates'
    | '/r/company'
    | '/r/dashboard'
    | '/r/onboarding'
    | '/r/settings'
    | '/r/signin'
    | '/r/signup'
    | '/r/team'
    | '/r/jobs/$id'
    | '/r/jobs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/businesses'
    | '/compliance'
    | '/contact'
    | '/dashboard'
    | '/imprint'
    | '/individuals'
    | '/onboarding'
    | '/privacy'
    | '/privacy-policy'
    | '/profile'
    | '/recruiters'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/matches/$id'
    | '/r/billing'
    | '/r/candidates'
    | '/r/company'
    | '/r/dashboard'
    | '/r/onboarding'
    | '/r/settings'
    | '/r/signin'
    | '/r/signup'
    | '/r/team'
    | '/r/jobs/$id'
    | '/r/jobs/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/businesses'
    | '/compliance'
    | '/contact'
    | '/dashboard'
    | '/imprint'
    | '/individuals'
    | '/onboarding'
    | '/privacy'
    | '/privacy-policy'
    | '/profile'
    | '/recruiters'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/matches/$id'
    | '/r/billing'
    | '/r/candidates'
    | '/r/company'
    | '/r/dashboard'
    | '/r/onboarding'
    | '/r/settings'
    | '/r/signin'
    | '/r/signup'
    | '/r/team'
    | '/r/jobs/$id'
    | '/r/jobs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessesRoute: typeof BusinessesRoute
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ImprintRoute: typeof ImprintRoute
  IndividualsRoute: typeof IndividualsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  RecruitersRoute: typeof RecruitersRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  MatchesIdRoute: typeof MatchesIdRoute
  RBillingRoute: typeof RBillingRoute
  RCandidatesRoute: typeof RCandidatesRoute
  RCompanyRoute: typeof RCompanyRoute
  RDashboardRoute: typeof RDashboardRoute
  ROnboardingRoute: typeof ROnboardingRoute
  RSettingsRoute: typeof RSettingsRoute
  RSigninRoute: typeof RSigninRoute
  RSignupRoute: typeof RSignupRoute
  RTeamRoute: typeof RTeamRoute
  RJobsIdRoute: typeof RJobsIdRoute
  RJobsNewRoute: typeof RJobsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiters': {
      id: '/recruiters'
      path: '/recruiters'
      fullPath: '/recruiters'
      preLoaderRoute: typeof RecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals': {
      id: '/individuals'
      path: '/individuals'
      fullPath: '/individuals'
      preLoaderRoute: typeof IndividualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/team': {
      id: '/r/team'
      path: '/r/team'
      fullPath: '/r/team'
      preLoaderRoute: typeof RTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/signup': {
      id: '/r/signup'
      path: '/r/signup'
      fullPath: '/r/signup'
      preLoaderRoute: typeof RSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/signin': {
      id: '/r/signin'
      path: '/r/signin'
      fullPath: '/r/signin'
      preLoaderRoute: typeof RSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/settings': {
      id: '/r/settings'
      path: '/r/settings'
      fullPath: '/r/settings'
      preLoaderRoute: typeof RSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/onboarding': {
      id: '/r/onboarding'
      path: '/r/onboarding'
      fullPath: '/r/onboarding'
      preLoaderRoute: typeof ROnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/dashboard': {
      id: '/r/dashboard'
      path: '/r/dashboard'
      fullPath: '/r/dashboard'
      preLoaderRoute: typeof RDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/company': {
      id: '/r/company'
      path: '/r/company'
      fullPath: '/r/company'
      preLoaderRoute: typeof RCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/candidates': {
      id: '/r/candidates'
      path: '/r/candidates'
      fullPath: '/r/candidates'
      preLoaderRoute: typeof RCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/billing': {
      id: '/r/billing'
      path: '/r/billing'
      fullPath: '/r/billing'
      preLoaderRoute: typeof RBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/jobs/new': {
      id: '/r/jobs/new'
      path: '/r/jobs/new'
      fullPath: '/r/jobs/new'
      preLoaderRoute: typeof RJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/jobs/$id': {
      id: '/r/jobs/$id'
      path: '/r/jobs/$id'
      fullPath: '/r/jobs/$id'
      preLoaderRoute: typeof RJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessesRoute: BusinessesRoute,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ImprintRoute: ImprintRoute,
  IndividualsRoute: IndividualsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  RecruitersRoute: RecruitersRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  MatchesIdRoute: MatchesIdRoute,
  RBillingRoute: RBillingRoute,
  RCandidatesRoute: RCandidatesRoute,
  RCompanyRoute: RCompanyRoute,
  RDashboardRoute: RDashboardRoute,
  ROnboardingRoute: ROnboardingRoute,
  RSettingsRoute: RSettingsRoute,
  RSigninRoute: RSigninRoute,
  RSignupRoute: RSignupRoute,
  RTeamRoute: RTeamRoute,
  RJobsIdRoute: RJobsIdRoute,
  RJobsNewRoute: RJobsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
